config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'applications#index'
  resources :applications, only: [ :index, :edit, :update, :show, :new, :create ] do
    resources :cover_paras, only: [ :create, :update, :destroy ]
    resources :values, only: [ :create, :destroy ]
    resources :competencies, only: [ :create, :destroy ]
  end
  resources :jobs, only: [ :index, :edit, :update ] do
    resources :bulletpoints, only: :create
    resources :quotes, only: :create
  end
  resources :bulletpoints, only: [ :destroy, :update ]
  resources :quotes, only: [ :destroy, :update ]
  post '/applications/:application_id/values/create', to: 'values#create_new', as: :create_new_value
  post '/applications/:application_id/competencies/create', to: 'competencies#create_new', as: :create_new_competency
end

app/models/app_competency.rb
class AppCompetency < ApplicationRecord
  belongs_to :application
  belongs_to :competency
end

app/models/app_cover_para.rb
class AppCoverPara < ApplicationRecord
  belongs_to :application
  belongs_to :cover_para
end

app/models/app_value.rb
class AppValue < ApplicationRecord
  belongs_to :application
  belongs_to :value
end

app/models/application.rb
class Application < ApplicationRecord
  has_many :app_competencies, dependent: :destroy
  has_many :competencies, through: :app_competencies
  has_many :app_cover_paras, dependent: :destroy
  has_many :cover_paras, through: :app_cover_paras
  has_many :app_values, dependent: :destroy
  has_many :values, through: :app_values
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bulletpoint.rb
class Bulletpoint < ApplicationRecord
  belongs_to :card, polymorphic: true
end

app/models/competency.rb
class Competency < ApplicationRecord
  has_many :app_competencies
end

app/models/cover_para.rb
class CoverPara < ApplicationRecord
  has_many :app_cover_paras, dependent: :destroy
  has_many :applications, through: :app_cover_paras
end

app/models/education.rb
class Education < ApplicationRecord
  has_many :bulletpoints, as: :card, dependent: :destroy
end

app/models/hobby.rb
class Hobby < ApplicationRecord
  has_many :bulletpoints, as: :card, dependent: :destroy
end

app/models/job.rb
class Job < ApplicationRecord
  has_many :bulletpoints, as: :card, dependent: :destroy
  has_many :quotes, dependent: :destroy
end

app/models/nav_tab.rb
class NavTab < ApplicationRecord
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :bulletpoints, as: :card, dependent: :destroy
end

app/models/quote.rb
class Quote < ApplicationRecord
  belongs_to :job
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/value.rb
class Value < ApplicationRecord
  has_many :app_values, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

end

app/controllers/applications_controller.rb
class ApplicationsController < ApplicationController
  skip_before_action :authenticate_user!, only: :show

  def index
    @applications = Application.all
  end

  def new
    @application = Application.new
  end

  def create
    @application = Application.new(application_params)
    if @application.save
      redirect_to edit_application_path(@application)
    else
      render :new
    end
  end

  def edit
    @application = Application.includes(:competencies, :cover_paras, :values).find(params[:id])
    @all_cover_paras = CoverPara.all.order(id: :asc)
    @other_values = Value.all.reject { |val| @application.values.include? val }
    @value = Value.new
    @other_competencies = Competency.all.reject { |comp| @application.competencies.include? comp }
    @competency = Competency.new
  end

  def update
    @application = Application.find(params[:id])
    @application.update(application_params)
    redirect_to edit_application_path(@application)
  end

  def show
    string_id = params[:id].downcase.gsub(/[^a-z]/, '')
    @application = Application.includes(:competencies, :cover_paras, :values).find_by_string_id(string_id)
    if @application&.passkey == params[:key]
      # nav_tabs = NavTab.all.map { |nav| { id: nav.title.downcase, title: nav.title, iconName: nav.icon_name }}
      jobs = format_jobs
      education = format_education
      hobbies = format_hobbies
      projects = format_projects
      values = format_values(@application)
      competencies = format_competencies(@application)

      render json: {
        logoUrl: @application.logo_url,
        jobTitle: @application.job_title,
        companyName: @application.company_name,
        primaryColor: @application.primary_color,
        secondaryColor: @application.secondary_color,
        backgroundColor: @application.background_color,
        headersFont: @application.headers_font,
        bodyFont: @application.body_font,
        fontLink: @application.font_link,
        # navTabs: nav_tabs,
        cover: @application.cover_paras,
        experience: jobs,
        education: education,
        hobbies: hobbies,
        projects: projects,
        values: values,
        competencies: competencies
      }
    else
      render json: {
        failure: 'company name and passkey fail to match'
      }
    end
  end

  private

  def application_params
    params.require(:application).permit(:job_title, :company_name, :logo_url, :primary_color, :secondary_color, :background_color, :headers_font, :body_font, :font_link, :string_id, :passkey)
  end

  def format_jobs
    Job.includes(:quotes, :bulletpoints).all.order(start_date: :desc).map do |job|
      {
        id: job.string_id,
        institution: job.institution,
        title: job.job_title,
        date: job.date_range,
        imageUrl: job.image_url,
        text: job.text,
        quotes: job.quotes.map { |q| { author: q.author, text: q.text } },
        bulletpoints: job.bulletpoints.map(&:text)
      }
    end
  end

  def format_education
    Education.includes(:bulletpoints).all.map do |edu|
      {
        id: edu.string_id,
        institution: edu.institution,
        title: edu.title,
        date: edu.date_range,
        imageUrl: edu.image_url,
        bulletpoints: edu.bulletpoints.map(&:text)
      }
    end
  end

  def format_hobbies
    Hobby.includes(:bulletpoints).all.map do |hobby|
      {
        id: hobby.string_id,
        title: hobby.title,
        imageUrl: hobby.image_url,
        bulletpoints: hobby.bulletpoints.map(&:text)
      }
    end
  end

  def format_projects
    Project.includes(:bulletpoints).all.map do |project|
      {
        id: project.string_id,
        title: project.title,
        imageUrl: project.image_url,
        url: project.url,
        bulletpoints: project.bulletpoints.map(&:text)
      }
    end
  end

  def format_values(application)
    application.values.map do |val|
      {
        id: val.title.downcase,
        title: val.title,
        text:val.text
      }
    end
  end

  def format_competencies(application)
    application.competencies.map do |comp|
      {
        id: comp.title.downcase,
        title: comp.title,
        imgUrl: comp.image_url,
        text: comp.text
      }
    end
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  def index
    @jobs = Job.includes(:quotes, :bulletpoints).all.order(start_date: :desc)
  end

  def edit
    @job = Job.includes(:quotes, :bulletpoints).find(params[:id])
    @bulletpoint = Bulletpoint.new
    @quote = Quote.new
  end

  def update
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/applications_helper.rb
module ApplicationsHelper
end

app/helpers/cover_paras_helper.rb
module CoverParasHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/helpers/values_helper.rb
module ValuesHelper
end

app/views/applications/edit.html.erb
<div class="flex justify-center">
  <div class="w-11/12 md:w-3/4 pt-4">
    <h1 class="text-center text-2xl">Application for <%= @application.job_title + ' at ' + @application.company_name %></h1>
    <ul class="flex justify-evenly border border-gray my-4 p-2 rounded-md">
      <li class="p-2 rounded-md border border-gray cursor-pointer hover:shadow" id="general-tab">General</li>
      <li class="p-2 rounded-md border border-gray cursor-pointer hover:shadow" id="cover-tab">Cover</li>
      <li class="p-2 rounded-md border border-gray cursor-pointer hover:shadow" id="values-tab">Values</li>
      <li class="p-2 rounded-md border border-black cursor-default" id="competencies-tab">Competencies</li>
    </ul>
    <div id="general-content" class="hidden">
      <%= render 'shared/basic_details_form', application: @application %>
    </div>
    <div id="cover-content" class="hidden">
      <div class="flex">
        <div class="w-7/12">
          <% if @application.cover_paras.empty? %>
            <%= form_tag application_cover_paras_path(@application), class: "flex flex-col items-center" do %>
              <%= text_area_tag 1, '', class: 'border rounded-md my-2 text-sm p-1 w-full' %>
              <%= text_area_tag 2, '', class: 'border rounded-md my-2 text-sm p-1 w-full' %>
              <%= text_area_tag 3, '', class: 'border rounded-md my-2 text-sm p-1 w-full' %>
              <%= text_area_tag 4, '', class: 'border rounded-md my-2 text-sm p-1 w-full' %>
              <%= text_area_tag 5, '', class: 'border rounded-md my-2 text-sm p-1 w-full' %>
              <%= text_area_tag 6, '', class: 'border rounded-md my-2 text-sm p-1 w-full' %>
              <%= submit_tag 'Save', class: "w-28 py-1 text-white rounded-lg bg-blue-700 hover:bg-purple-900 shadow-lg" %>
            <% end %>
          <% else %>
            <%= form_tag application_cover_paras_path(@application), class: "flex flex-col items-center" do %>
              <% @application.app_cover_paras.each do |app_para| %>
                <div class="flex items-center w-full">
                  <%= text_area_tag app_para.order, app_para.cover_para.text, class: 'border rounded-md my-1 text-sm p-1 flex-grow' %>
                  <%= link_to 'x', application_cover_para_path(@application, app_para), method: :delete, class: "w-6 h-6 text-center bg-red-700 text-white rounded-full" %>
                </div>
              <% end %>
              <%= text_area_tag @application.cover_paras.count + 1, '', class: 'border rounded-md my-2 text-sm p-1 w-full' %>
              <%= submit_tag 'Save', class: "w-28 py-1 text-white rounded-lg bg-blue-700 hover:bg-purple-900 shadow-lg" %>
            <% end %>
          <% end %>
        </div>
        <div class="w-5/12">
          <% @all_cover_paras.each do |para| %>
            <p class="m-2 p-1 border border-gray rounded-md text-sm">
              <%= para.text %>
            </p>
          <% end %>
        </div>
      </div>
    </div>
    <div id="values-content" class="hidden">
      <%= form_with model: @value, url: create_new_value_path(@application), method: :post, class: "flex items-center" do |f| %>
        <div class="flex flex-col w-80">
          <%= f.label :title %>
          <%= f.text_field :title, class: "border rounded-md m-2" %>
          <%= f.label :image_url %>
          <%= f.text_field :image_url, class: "border rounded-md m-2" %>
        </div>
        <%= f.text_area :text, class: "border rounded-md m-2 w-96 h-36" %>
        <%= f.submit 'Create', class: 'bg-indigo-400 hover:bg-indigo-600 cursor-pointer text-white h-12 w-24 mx-2 rounded-md' %>
      <% end %>
      <div class="flex">
        <div class="w-1/2 mr-2">
          <% @application.values.each do |val| %>
            <%= render 'shared/value_card', value: val, app: @application, now_in: true %>
          <% end %>
        </div>
        <div class="w-1/2">
          <% @other_values.each do |val| %>
            <%= render 'shared/value_card', value: val, app: @application, now_in: false %>
          <% end %>
        </div>
      </div>
    </div>
    <div id="competencies-content" class="flex flex-col items-center">
      <%= form_with model: @competency, url: create_new_competency_path(@application), method: :post, class: "flex items-center" do |f| %>
        <div class="flex flex-col w-80">
          <%= f.label :title %>
          <%= f.text_field :title, class: "border rounded-md m-2" %>
          <%= f.label :image_url %>
          <%= f.text_field :image_url, class: "border rounded-md m-2" %>
        </div>
        <%= f.text_area :text, class: "border rounded-md m-2 w-96 h-36" %>
        <%= f.submit 'Create', class: 'bg-indigo-400 hover:bg-indigo-600 cursor-pointer text-white h-12 w-24 mx-2 rounded-md' %>
      <% end %>
      <div class="flex">
        <div class="w-1/2 mr-2">
          <% @application.competencies.each do |comp| %>
            <%= render 'shared/competency_card', competency: comp, app: @application, now_in: true %>
          <% end %>
        </div>
        <div class="w-1/2">
          <% @other_competencies.each do |comp| %>
            <%= render 'shared/competency_card', competency: comp, app: @application, now_in: false %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

<script>
  const toggleHidden = tab => tab.classList.toggle('hidden')
  const toggleButtonClasses = (btn) => {
    btn.classList.toggle('border-black')
    btn.classList.toggle('border-gray')
    btn.classList.toggle('cursor-pointer')
    btn.classList.toggle('cursor-default')
    btn.classList.toggle('hover:shadow')
  }
  const getContentDiv = (tabId) => {
    const divId = tabId.split('-')[0] + '-content'
    return document.getElementById(divId)
  }
  const tabs = document.querySelectorAll('li')
  tabs.forEach((tab) => {
    tab.addEventListener('click', (e) => {
      const activeTab = Array.from(tabs).filter(tab => tab.classList.contains('border-black'))[0]
      toggleButtonClasses(activeTab)
      toggleButtonClasses(e.currentTarget)
      const divToReveal = getContentDiv(e.currentTarget.id)
      const divToHide = getContentDiv(activeTab.id)
      toggleHidden(divToHide)
      toggleHidden(divToReveal)
    })
  })
</script>

app/views/applications/index.html.erb
<div class="flex justify-center">
  <div class="w-11/12 md:w-3/4 pt-4">
    <h1 class="text-2xl text-center">Applications</h1>

    <% @applications.each do |app| %>
      <%= link_to edit_application_path(app) do %>
        <div class="m-2 p-2 border border-gray rounded-lg hover:border-black">
          <h2><%= app.job_title %> </h2>
          <h3><%= app.company_name %> </h3>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/applications/new.html.erb
<div class="flex justify-center">
  <div class="w-11/12 md:w-3/4 pt-4">
    <%= render 'shared/basic_details_form', application: @application %>
  </div>
</div>