config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'applications#index'
  resources :applications, only: [ :index, :edit, :update, :show, :new, :create ] do
    resources :cover_paras, only: [ :create, :update, :destroy ]
    resources :values, only: [ :create, :destroy ]
    resources :competencies, only: [ :create, :destroy ]
  end
  resources :jobs, only: [ :index, :edit, :update ] do
    resources :bulletpoints, only: :create
    resources :quotes, only: :create
  end
  resources :bulletpoints, only: [ :destroy, :update ]
  resources :quotes, only: [ :destroy, :update ]
  post '/applications/:application_id/values/create', to: 'values#create_new', as: :create_new_value
  post '/applications/:application_id/competencies/create', to: 'competencies#create_new', as: :create_new_competency
end

app/models/app_competency.rb
class AppCompetency < ApplicationRecord
  belongs_to :application
  belongs_to :competency
end

app/models/app_cover_para.rb
class AppCoverPara < ApplicationRecord
  belongs_to :application
  belongs_to :cover_para
end

app/models/app_value.rb
class AppValue < ApplicationRecord
  belongs_to :application
  belongs_to :value
end

app/models/application.rb
class Application < ApplicationRecord
  has_many :app_competencies, dependent: :destroy
  has_many :competencies, through: :app_competencies
  has_many :app_cover_paras, dependent: :destroy
  has_many :cover_paras, through: :app_cover_paras
  has_many :app_values, dependent: :destroy
  has_many :values, through: :app_values
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bulletpoint.rb
class Bulletpoint < ApplicationRecord
  belongs_to :card, polymorphic: true
end

app/models/competency.rb
class Competency < ApplicationRecord
  has_many :app_competencies
end

app/models/cover_para.rb
class CoverPara < ApplicationRecord
  has_many :app_cover_paras, dependent: :destroy
  has_many :applications, through: :app_cover_paras
end

app/models/education.rb
class Education < ApplicationRecord
  has_many :bulletpoints, as: :card, dependent: :destroy
end

app/models/hobby.rb
class Hobby < ApplicationRecord
  has_many :bulletpoints, as: :card, dependent: :destroy
end

app/models/job.rb
class Job < ApplicationRecord
  has_many :bulletpoints, as: :card, dependent: :destroy
  has_many :quotes, dependent: :destroy
end

app/models/nav_tab.rb
class NavTab < ApplicationRecord
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :bulletpoints, as: :card, dependent: :destroy
end

app/models/quote.rb
class Quote < ApplicationRecord
  belongs_to :job
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/value.rb
class Value < ApplicationRecord
  has_many :app_values, dependent: :destroy
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  def index
    @jobs = Job.includes(:quotes, :bulletpoints).all.order(start_date: :desc)
  end

  def edit
    @job = Job.includes(:quotes, :bulletpoints).find(params[:id])
    @bulletpoint = Bulletpoint.new
    @quote = Quote.new
  end

  def update
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/applications_helper.rb
module ApplicationsHelper
end

app/helpers/cover_paras_helper.rb
module CoverParasHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/helpers/values_helper.rb
module ValuesHelper
end

app/views/jobs/edit.html.erb
<div class="flex flex-col p-12">
  <%= form_for(@job) do |f| %>
    <div class="flex justify-center">
      <div class="p-2">
        <%= f.label :string_id, 'String ID' %>
        <%= f.text_field :string_id, class: "rounded-lg border-gray-500" %>
      </div>
      <div class="p-2">
        <%= f.label :institution %>
        <%= f.text_field :institution, class: "rounded-lg border-gray-500" %>
      </div>
      <div class="p-2">
        <%= f.label :job_title %>
        <%= f.text_field :job_title, class: "rounded-lg border-gray-500 w-96" %>
      </div>
    </div>
    <div class="flex justify-center">
      <div class="p-2">
        <%= f.label :image_url %>
        <%= f.text_field :image_url, class: "rounded-lg border-gray-500" %>
      </div>
      <div class="p-2">
        <%= f.label :date_range %>
        <%= f.text_field :date_range, class: "rounded-lg border-gray-500" %>
      </div>
      <div class="p-2">
        <%= f.label :start_date %>
        <%= f.date_field :start_date, class: "rounded-lg border-gray-500" %>
      </div>
    </div>
    <div class="flex justify-center">
      <div class="p-2 w-2/3">
        <%= f.label :text %>
        <%= f.text_area :text, class: "rounded-lg border-gray-500 w-full h-28" %>
      </div>
    </div>
    <div class="flex justify-end">
      <%= f.submit class: 'py-3 px-6 mr-48 text-white rounded-lg bg-purple-700 hover:bg-purple-900 shadow-lg cursor-pointer' %>
    </div>
  <% end %>
  <h4 class="ml-48 text-lg my-2">Bulletpoints:</h4>
  <% @job.bulletpoints.each do |point| %>
    <div class="flex justify-center my-1">
      <div class="w-1/2">
        <%= form_for(point, html: { method: :patch, class: 'flex items-center' }) do |f| %>
          <%= f.text_area :text, class: "flex-grow text-sm rounded-md" %>
          <%= f.submit 'Update', class: 'py-1 px-2 mx-2 text-white rounded-md bg-green-700 hover:bg-green-600 shadow-lg cursor-pointer' %>
        <% end %>
      </div>
      <div class="w-1/5 flex items-center">
        <%= link_to 'Delete', bulletpoint_path(point), method: :delete, class: 'py-1 px-2 mx-2 text-white rounded-md bg-red-700 hover:bg-red-600 shadow-lg cursor-pointer' %>
      </div>
    </div>
  <% end %>
  <%= form_for(@bulletpoint, url: job_bulletpoints_path(@job), html: { class: 'flex items-center my-1 w-1/2 self-center' }) do |f| %>
    <%= f.text_area :text, class: "flex-grow text-sm rounded-md" %>
    <%= f.submit 'Create', class: 'py-1 px-2 mx-2 text-white rounded-md bg-green-700 hover:bg-green-600 shadow-lg cursor-pointer' %>
  <% end %>
  <h4 class="ml-48 text-lg my-2">Quotes:</h4>
  <% @job.quotes.each do |quote| %>
    <div class="flex justify-center my-1">
      <div class="w-2/3">
        <%= form_for(quote, html: { method: :patch, class: 'flex items-center' }) do |f| %>
          <div class="flex flex-col">
            <%= f.label :author %>
            <%= f.text_field :author, class: "text-sm rounded-md mx-2" %>
          </div>
          <%= f.text_area :text, class: "flex-grow text-sm rounded-md mx-2 h-20" %>
          <%= f.submit 'Update', class: 'py-1 px-2 mx-2 text-white rounded-md bg-green-700 hover:bg-green-600 shadow-lg cursor-pointer' %>
        <% end %>
      </div>
      <div class="w-1/5 flex items-center">
        <%= link_to 'Delete', quote_path(quote), method: :delete, class: 'py-1 px-2 mx-2 text-white rounded-md bg-red-700 hover:bg-red-600 shadow-lg cursor-pointer' %>
      </div>
    </div>
  <% end %>
  <%= form_for(@quote, url: job_quotes_path(@job), html: { class: 'flex items-center my-1 w-1/2 self-center' }) do |f| %>
    <div class="flex flex-col">
      <%= f.label :author %>
      <%= f.text_field :author, class: "text-sm rounded-md mx-2" %>
    </div>
    <%= f.text_area :text, class: "flex-grow text-sm rounded-md mx-2 h-20" %>
    <%= f.submit 'Create', class: 'py-1 px-2 mx-2 text-white rounded-md bg-green-700 hover:bg-green-600 shadow-lg cursor-pointer' %>
  <% end %>
</div>

app/views/jobs/index.html.erb
<div class="flex justify-center">
  <div class="w-11/12 md:w-3/4 pt-4">
    <ul class="flex justify-evenly border border-gray my-4 p-2 rounded-md">
      <li class="p-2 rounded-md border border-black cursor-default" id="experience-tab">Experience</li>
      <li class="p-2 rounded-md border border-gray cursor-pointer hover:shadow" id="education-tab">Education</li>
      <li class="p-2 rounded-md border border-gray cursor-pointer hover:shadow" id="projects-tab">Projects</li>
    </ul>
    <div id="experience-content" class="flex flex-col items-center">
      <% @jobs.each do |job| %>
        <%= render 'shared/job_card', job: job %>
      <% end %>
    </div>
    <div id="education-content" class="hidden">edu</div>
    <div id="projects-content" class="hidden">projecs</div>
  </div>
</div>

<script>
  const toggleHidden = tab => tab.classList.toggle('hidden')
  const toggleButtonClasses = (btn) => {
    btn.classList.toggle('border-black')
    btn.classList.toggle('border-gray')
    btn.classList.toggle('cursor-pointer')
    btn.classList.toggle('cursor-default')
    btn.classList.toggle('hover:shadow')
  }
  const getContentDiv = (tabId) => {
    const divId = tabId.split('-')[0] + '-content'
    return document.getElementById(divId)
  }
  const tabs = document.querySelectorAll('li')
  tabs.forEach((tab) => {
    tab.addEventListener('click', (e) => {
      const activeTab = Array.from(tabs).filter(tab => tab.classList.contains('border-black'))[0]
      toggleButtonClasses(activeTab)
      toggleButtonClasses(e.currentTarget)
      const divToReveal = getContentDiv(e.currentTarget.id)
      const divToHide = getContentDiv(activeTab.id)
      toggleHidden(divToHide)
      toggleHidden(divToReveal)
    })
  })
</script>