config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'applications#index'
  resources :applications, only: [ :index, :edit, :update, :show, :new, :create ] do
    resources :cover_paras, only: [ :create, :update, :destroy ]
    resources :values, only: [ :create, :destroy ]
    resources :competencies, only: [ :create, :destroy ]
  end
  resources :jobs, only: [ :index, :edit, :update ] do
    resources :bulletpoints, only: :create
    resources :quotes, only: :create
  end
  resources :bulletpoints, only: [ :destroy, :update ]
  resources :quotes, only: [ :destroy, :update ]
  post '/applications/:application_id/values/create', to: 'values#create_new', as: :create_new_value
  post '/applications/:application_id/competencies/create', to: 'competencies#create_new', as: :create_new_competency
end

app/models/app_competency.rb
class AppCompetency < ApplicationRecord
  belongs_to :application
  belongs_to :competency
end

app/models/app_cover_para.rb
class AppCoverPara < ApplicationRecord
  belongs_to :application
  belongs_to :cover_para
end

app/models/app_value.rb
class AppValue < ApplicationRecord
  belongs_to :application
  belongs_to :value
end

app/models/application.rb
class Application < ApplicationRecord
  has_many :app_competencies, dependent: :destroy
  has_many :competencies, through: :app_competencies
  has_many :app_cover_paras, dependent: :destroy
  has_many :cover_paras, through: :app_cover_paras
  has_many :app_values, dependent: :destroy
  has_many :values, through: :app_values
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bulletpoint.rb
class Bulletpoint < ApplicationRecord
  belongs_to :card, polymorphic: true
end

app/models/competency.rb
class Competency < ApplicationRecord
  has_many :app_competencies
end

app/models/cover_para.rb
class CoverPara < ApplicationRecord
  has_many :app_cover_paras, dependent: :destroy
  has_many :applications, through: :app_cover_paras
end

app/models/education.rb
class Education < ApplicationRecord
  has_many :bulletpoints, as: :card, dependent: :destroy
end

app/models/hobby.rb
class Hobby < ApplicationRecord
  has_many :bulletpoints, as: :card, dependent: :destroy
end

app/models/job.rb
class Job < ApplicationRecord
  has_many :bulletpoints, as: :card, dependent: :destroy
  has_many :quotes, dependent: :destroy
end

app/models/nav_tab.rb
class NavTab < ApplicationRecord
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :bulletpoints, as: :card, dependent: :destroy
end

app/models/quote.rb
class Quote < ApplicationRecord
  belongs_to :job
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/value.rb
class Value < ApplicationRecord
  has_many :app_values, dependent: :destroy
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/helpers/values_helper.rb
module ValuesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JobApps</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "inter-font" %>
    <%= stylesheet_link_tag "tailwind" %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/shared/_basic_details_form.html.erb
<%= form_for application, html: { class: 'flex flex-col' } do |f| %>
  <div class="flex flex-wrap justify-around">
    <div class="w-1/4 mx-2 my-2">
      <%= f.label :job_title, class: 'block' %>
      <%= f.text_field :job_title, class: 'block w-full' %>
    </div>
    <div class="w-1/4 mx-2 my-2">
      <%= f.label :company_name, class: 'block' %>
      <%= f.text_field :company_name, class: 'block w-full' %>
    </div>
    <div class="w-1/4 mx-2 my-2">
      <%= f.label :logo_url, class: 'block' %>
      <%= f.text_field :logo_url, class: 'block w-full' %>
    </div>
    <div class="w-1/4 mx-2 my-2">
      <%= f.label :primary_color, class: 'block' %>
      <%= f.text_field :primary_color, class: 'block w-full' %>
    </div>
    <div class="w-1/4 mx-2 my-2">
      <%= f.label :secondary_color, class: 'block' %>
      <%= f.text_field :secondary_color, class: 'block w-full' %>
    </div>
    <div class="w-1/4 mx-2 my-2">
      <%= f.label :background_color, class: 'block' %>
      <%= f.text_field :background_color, class: 'block w-full' %>
    </div>
    <div class="w-1/4 mx-2 my-2">
      <%= f.label :headers_font, class: 'block' %>
      <%= f.text_field :headers_font, class: 'block w-full' %>
    </div>
    <div class="w-1/4 mx-2 my-2">
      <%= f.label :body_font, class: 'block' %>
      <%= f.text_field :body_font, class: 'block w-full' %>
    </div>
    <div class="w-1/4 mx-2 my-2">
      <%= f.label :font_link, class: 'block' %>
      <%= f.text_field :font_link, class: 'block w-full' %>
    </div>
    <div class="w-1/4 mx-2 my-2">
      <%= f.label :string_id, 'String ID', class: 'block' %>
      <%= f.text_field :string_id, class: 'block w-full' %>
    </div>
    <div class="w-1/4 mx-2 my-2">
      <%= f.label :passkey, class: 'block' %>
      <%= f.text_field :passkey, class: 'block w-full' %>
    </div>
  </div>
  <%= f.submit class: 'py-3 px-6 mx-3 text-white rounded-lg bg-purple-700 hover:bg-purple-900 shadow-lg self-end' %>
<% end %>

app/views/shared/_competency_card.html.erb
<div class="my-2 p-2 pb-4 flex flex-col border-b border-blue-700 border-opacity-50">
  <div class="mb-2 flex items-center pl-2 pb-2">
    <% if competency.image_url %>
      <img src=<%= competency.image_url %> class="h-12 w-12 mr-2 rounded-md object-cover object-center">
    <% end %>
    <p class="font-headers text-lg font-light text-background"><%= competency.title %></p>
    <% if now_in %>
      <%= link_to 'Remove', application_competency_path(app, competency), method: :delete, class: 'bg-red-700 text-white py-1 px-2 mx-2 rounded-sm' %>
    <% else %>
      <%= link_to 'Add', application_competencies_path(app, competency_id: competency), method: :post, class: 'bg-green-500 text-white py-1 px-2 mx-2 rounded-sm' %>
    <% end %>
  </div>
  <div class="w-5/6 self-end flex border border-red-700 border-opacity-20 rounded-md p-2">
    <p class="font-body italic text-background text-right"><%= competency.text %></p>
  </div>
</div>

app/views/shared/_job_card.html.erb
<div class="my-2 border border-blue-900 border-opacity-20 rounded-md p-2 w-2/3 relative">
  <%= link_to 'Edit', edit_job_path(job), class: 'absolute top-16 -right-20 bg-green-500 hover:bg-green-700 border-2 border-pink-700 hover:border-pink-500 text-white py-2 px-4 rounded-md' %>
  <div class="flex">
    <img src=<%= job.image_url %> alt=<%= job.image_url %> class="h-20 w-20 rounded-md">
    <div class="flex-grow pl-2 flex flex-col justify-evenly">
      <h4 class="font-headers font-light text-blue-900 text-base sm:text-lg md:text-2xl"><%= job.job_title %></h4>
      <h4 class="font-headers font-bold text-blue-900 text-sm sm:text-base md:text-lg"><%= job.institution %></h4>
      <h4 class="font-headers italic text-blue-900 text-xs sm:text-sm md:text-base"><%= job.date_range %></h4>
    </div>
  </div>
  <p class="font-body text-blue-900 mt-2"><%= job.text %></p>
  <div>
    <ul class="list-disc pl-6">
      <% job.bulletpoints.each do |bp| %>
        <li class="font-body text-blue-900 font-light text-sm"><%= bp.text %></li>
      <% end %>
    </ul>
    <% job.quotes.each do |q| %>
      <div class="my-1 text-sm mx-2">
        <p class="font-body text-blue-900 italic">"<%= q.text %>"</p>
        <p class="font-body text-blue-900 font-bold text-right mr-6"><%= q.author %></p>
      </div>
    <% end %>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="h-16 bg-blue-400 flex justify-center items-center">
  <%= link_to 'Applications', applications_path, class: 'py-3 px-6 mx-3 text-white rounded-lg bg-purple-700 hover:bg-purple-900 shadow-lg' %>
  <%= link_to 'New Application', new_application_path, class: 'py-3 px-6 mx-3 text-white rounded-lg bg-purple-700 hover:bg-purple-900 shadow-lg' %>
  <%= link_to 'Edit Constants', jobs_path, class: 'py-3 px-6 mx-3 text-white rounded-lg bg-purple-700 hover:bg-purple-900 shadow-lg' %>
  <% if user_signed_in? %>
    <%= link_to 'Sign out', destroy_user_session_path, class: 'py-3 px-6 mx-3 text-white rounded-lg bg-red-700 hover:bg-purple-900 shadow-lg' %>
  <% else %>
    <%= link_to 'Sign in', new_user_session_path, class: 'py-3 px-6 mx-3 text-white rounded-lg bg-green-700 hover:bg-purple-900 shadow-lg' %>
  <% end %>
</div>

app/views/shared/_value_card.html.erb
<div class="my-2 p-2 pb-4 flex flex-col border-b border-blue-700 border-opacity-50">
  <div class="mb-2 flex items-center pl-2 pb-2">
    <% if value.image_url %>
      <img src=<%= value.image_url %> class="h-12 w-12 mr-2 rounded-md object-cover object-center">
    <% end %>
    <p class="font-headers text-lg font-light text-background"><%= value.title %></p>
    <% if now_in %>
      <%= link_to 'Remove', application_value_path(app, value), method: :delete, class: 'bg-red-700 text-white py-1 px-2 mx-2 rounded-sm' %>
    <% else %>
      <%= link_to 'Add', application_values_path(app, value_id: value), method: :post, class: 'bg-green-500 text-white py-1 px-2 mx-2 rounded-sm' %>
    <% end %>
  </div>
  <div class="w-5/6 self-end flex border border-red-700 border-opacity-20 rounded-md p-2">
    <p class="font-body italic text-background text-right"><%= value.text %></p>
  </div>
</div>